import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { type OrbitDocsConfig, type OrbitDocsConfigInput, resolveConfig } from '@orbitdocs/core';
import { createMDX } from 'fumadocs-mdx/next';
import type { NextConfig } from 'next';

/**
 * Next config for an OrbitDocs site:
 * - `output.mode: 'static'` → `output: 'export'` (plain files for any host, or Nest),
 *   trailing slashes (folder/index.html) and unoptimised images;
 * - `output.basePath` → Next `basePath`;
 * - redirects (server mode; static builds get redirect pages from the CLI);
 * - MDX through fumadocs-mdx.
 */
/**
 * CSS for the configured theme, written to `.orbitdocs/theme.css` (imported by
 * app/global.css): the Fumadocs preset, the layout's CSS, the palette that ties
 * HeroUI and Fumadocs together, accent and widths.
 */
export function themeCss(config: OrbitDocsConfig): string {
  const { preset, accent, widths } = config.theme;
  const orbit = preset === 'orbit';
  const vars: string[] = [];
  if (widths.layout) vars.push(`--fd-layout-width: ${widths.layout};`);
  if (widths.sidebar) vars.push(`--fd-sidebar-width: ${widths.sidebar};`);
  if (widths.toc) vars.push(`--fd-toc-width: ${widths.toc};`);
  const lines = [
    '/* Generated by @orbitdocs/next from orbitdocs.config.ts. Do not edit; change the config. */',
    `@import 'fumadocs-ui/css/${orbit ? 'neutral' : preset}.css';`,
    `@import 'fumadocs-ui/css/preset.css';`,
    ...(config.layout.type === 'glass' ? [`@import 'fumadocs-ui/css/generated/glass.css';`] : []),
    `@import '@orbitdocs/ui/palette-${orbit ? 'orbit' : 'fumadocs'}.css';`,
  ];
  if (accent) {
    lines.push(
      orbit
        ? `:root, .dark { --od-accent: ${accent}; }`
        : `:root, .dark { --color-fd-primary: ${accent}; }`,
    );
  }
  if (vars.length) lines.push(`:root { ${vars.join(' ')} }`);
  return `${lines.join('\n')}\n`;
}

function writeTheme(config: OrbitDocsConfig, dir = process.cwd()) {
  const file = join(dir, '.orbitdocs', 'theme.css');
  const css = themeCss(config);
  let current = '';
  try {
    current = readFileSync(file, 'utf8');
  } catch {
    /* first run */
  }
  if (current !== css) {
    mkdirSync(join(dir, '.orbitdocs'), { recursive: true });
    writeFileSync(file, css);
  }
}

export function withOrbitDocs(orbit: OrbitDocsConfigInput, next: NextConfig = {}): NextConfig {
  const config = resolveConfig(orbit);
  writeTheme(config);
  const isStatic = config.output.mode === 'static';
  const base: NextConfig = {
    reactStrictMode: true,
    ...next,
    experimental: {
      // Turbopack's production scope hoisting (Next 16.3) can attach a react-aria
      // module's exports to the wrong module, so HeroUI overlays (Modal, Drawer)
      // fail to prerender with "useOverlayTrigger is not a function".
      turbopackScopeHoisting: false,
      ...next.experimental,
    },
    ...(config.output.basePath ? { basePath: config.output.basePath } : {}),
    env: {
      ...next.env,
      ORBITDOCS_BASE_PATH: config.output.basePath,
    },
    ...(isStatic
      ? {
          output: 'export',
          trailingSlash: true,
          images: { ...next.images, unoptimized: true },
        }
      : {
          // Same URLs as a static build.
          trailingSlash: true,
          async redirects() {
            const own = (await next.redirects?.()) ?? [];
            return [
              ...own,
              ...config.redirects.map((r) => ({
                source: r.from.replace(/\*$/, ':path*'),
                destination: r.to.replace(/\*$/, ':path*'),
                permanent: r.permanent,
              })),
            ];
          },
        }),
  };
  return createMDX()(base);
}
